// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvstore.proto

package kvstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// You'll likely need to define more specific return codes than these!
type ReturnCode int32

const (
	ReturnCode_SUCCESS ReturnCode = 0
	ReturnCode_FAILURE ReturnCode = 1
	// PUT return code
	ReturnCode_FAILURE_DEMOTED ReturnCode = 2
	ReturnCode_FAILURE_EXPIRED ReturnCode = 3
	ReturnCode_SUCCESS_SEQNO   ReturnCode = 4
)

var ReturnCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
	2: "FAILURE_DEMOTED",
	3: "FAILURE_EXPIRED",
	4: "SUCCESS_SEQNO",
}

var ReturnCode_value = map[string]int32{
	"SUCCESS":         0,
	"FAILURE":         1,
	"FAILURE_DEMOTED": 2,
	"FAILURE_EXPIRED": 3,
	"SUCCESS_SEQNO":   4,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_088d7f6aff848d9e, []int{0}
}

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_088d7f6aff848d9e, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                string     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ret                  ReturnCode `protobuf:"varint,2,opt,name=ret,proto3,enum=kvstore.ReturnCode" json:"ret,omitempty"`
	LeaderHint           string     `protobuf:"bytes,3,opt,name=leaderHint,proto3" json:"leaderHint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_088d7f6aff848d9e, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetResponse) GetRet() ReturnCode {
	if m != nil {
		return m.Ret
	}
	return ReturnCode_SUCCESS
}

func (m *GetResponse) GetLeaderHint() string {
	if m != nil {
		return m.LeaderHint
	}
	return ""
}

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	From                 int32    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	ClientId             string   `protobuf:"bytes,4,opt,name=clientId,proto3" json:"clientId,omitempty"`
	SeqNo                int32    `protobuf:"varint,5,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_088d7f6aff848d9e, []int{2}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PutRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *PutRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *PutRequest) GetSeqNo() int32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

type PutResponse struct {
	Ret                  ReturnCode `protobuf:"varint,1,opt,name=ret,proto3,enum=kvstore.ReturnCode" json:"ret,omitempty"`
	LeaderHint           string     `protobuf:"bytes,2,opt,name=leaderHint,proto3" json:"leaderHint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_088d7f6aff848d9e, []int{3}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetRet() ReturnCode {
	if m != nil {
		return m.Ret
	}
	return ReturnCode_SUCCESS
}

func (m *PutResponse) GetLeaderHint() string {
	if m != nil {
		return m.LeaderHint
	}
	return ""
}

func init() {
	proto.RegisterEnum("kvstore.ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterType((*GetRequest)(nil), "kvstore.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "kvstore.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "kvstore.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "kvstore.PutResponse")
}

func init() { proto.RegisterFile("kvstore.proto", fileDescriptor_088d7f6aff848d9e) }

var fileDescriptor_088d7f6aff848d9e = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0x2d, 0x7c, 0x7c, 0x0e, 0x41, 0xeb, 0xc0, 0xa1, 0xe1, 0x40, 0x48, 0x13, 0x13, 0xe2,
	0x81, 0x03, 0xfe, 0x02, 0x03, 0x2b, 0x12, 0x15, 0x70, 0x0b, 0xc6, 0x1b, 0x41, 0x18, 0x13, 0x04,
	0xbb, 0xd0, 0x6e, 0x31, 0xf8, 0xeb, 0xcd, 0x2e, 0xd5, 0xae, 0x26, 0x1e, 0xbc, 0xed, 0x9b, 0xdd,
	0xf7, 0xde, 0xbc, 0x99, 0x85, 0xf2, 0x6a, 0x17, 0x4b, 0x11, 0x51, 0x6b, 0x13, 0x09, 0x29, 0xb0,
	0x98, 0x42, 0xbf, 0x0e, 0xd0, 0x23, 0xc9, 0x69, 0x9b, 0x50, 0x2c, 0xd1, 0x05, 0x67, 0x45, 0x7b,
	0xcf, 0x6a, 0x58, 0xcd, 0x23, 0xae, 0x8e, 0xfe, 0x0b, 0x94, 0xf4, 0x7d, 0xbc, 0x11, 0x61, 0x4c,
	0x58, 0x85, 0xc2, 0x6e, 0xb6, 0x4e, 0x28, 0x7d, 0x72, 0x00, 0x78, 0x06, 0x4e, 0x44, 0xd2, 0xb3,
	0x1b, 0x56, 0xf3, 0xb8, 0x5d, 0x69, 0x7d, 0x5a, 0x71, 0x92, 0x49, 0x14, 0x76, 0xc4, 0x82, 0xb8,
	0xba, 0xc7, 0x3a, 0xc0, 0x9a, 0x66, 0x0b, 0x8a, 0xae, 0x97, 0xa1, 0xf4, 0x1c, 0xad, 0x60, 0x54,
	0xfc, 0x77, 0x80, 0x51, 0xf2, 0x7b, 0x2f, 0x99, 0xb9, 0x6d, 0x9a, 0x23, 0xe4, 0x9f, 0x23, 0xf1,
	0xaa, 0xf5, 0x0a, 0x5c, 0x9f, 0xb1, 0x06, 0xff, 0xe7, 0xeb, 0x25, 0x85, 0xb2, 0xbf, 0xf0, 0xf2,
	0xfa, 0xf1, 0x17, 0x56, 0x2a, 0x31, 0x6d, 0x07, 0xc2, 0x2b, 0x68, 0xc2, 0x01, 0xf8, 0x63, 0x28,
	0x69, 0xef, 0x34, 0x67, 0x9a, 0xc8, 0xfa, 0x53, 0x22, 0xfb, 0x67, 0xa2, 0xf3, 0x39, 0x40, 0x46,
	0xc1, 0x12, 0x14, 0x83, 0x49, 0xa7, 0xc3, 0x82, 0xc0, 0xcd, 0x29, 0x70, 0x75, 0xd9, 0xbf, 0x9d,
	0x70, 0xe6, 0x5a, 0x58, 0x81, 0x93, 0x14, 0x4c, 0xbb, 0xec, 0x6e, 0x38, 0x66, 0x5d, 0xd7, 0x36,
	0x8b, 0xec, 0x71, 0xd4, 0xe7, 0xac, 0xeb, 0x3a, 0x78, 0x0a, 0xe5, 0x54, 0x63, 0x1a, 0xb0, 0xfb,
	0xc1, 0xd0, 0xcd, 0xb7, 0xdf, 0xa0, 0x7c, 0x43, 0xfb, 0x07, 0x35, 0x8c, 0x40, 0x75, 0x89, 0x6d,
	0x70, 0x7a, 0x24, 0x31, 0x6b, 0x3b, 0xdb, 0x70, 0xad, 0xfa, 0xbd, 0x78, 0x88, 0xeb, 0xe7, 0x14,
	0x67, 0x94, 0x98, 0x9c, 0x6c, 0x13, 0x06, 0xc7, 0x18, 0x91, 0x9f, 0x7b, 0xfa, 0xa7, 0xff, 0xd2,
	0xc5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x5d, 0x68, 0x7c, 0x5c, 0x02, 0x00, 0x00,
}
